<a href="https://colab.research.google.com/github/ealger22/main/blob/CSC-302-Data-Visualization/lego_setsHB_ICA4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
!ls "/content/drive/My Drive/"

'Colab Notebooks'   lego_setsHB.csv   olympic_medals.csv

In [21]:
import pandas as pd

# Define the correct file path
file_path = "/content/drive/My Drive/lego_setsHB.csv"  # Modify based on location

# Read the dataset
df = pd.read_csv(file_path)

# Display first 5 rows
df.head()

,list_price,num_reviews,piece_count,play_star_rating,prod_id,review_difficulty,star_rating,val_star_rating
0,29.99,2.0,277,4.0,75823,Average,4.5,4.0
1,19.99,2.0,168,4.0,75822,Easy,5.0,4.0
2,12.99,11.0,74,4.3,75821,Easy,4.3,4.1
3,99.99,23.0,1032,3.6,21030,Average,4.6,4.3
4,79.99,14.0,744,3.2,21035,Challenging,4.6,4.1

In [22]:
# Get dataset information
df.info()

# Get summary statistics
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   list_price         12261 non-null  float64
 1   num_reviews        10641 non-null  float64
 2   piece_count        12261 non-null  int64
 3   play_star_rating   10486 non-null  float64
 4   prod_id            12261 non-null  int64
 5   review_difficulty  10206 non-null  object
 6   star_rating        10641 non-null  float64
 7   val_star_rating    10466 non-null  float64
dtypes: float64(5), int64(2), object(1)
memory usage: 766.4+ KB

,list_price,num_reviews,piece_count,play_star_rating,prod_id,star_rating,val_star_rating
count,12261.000000,10641.000000,12261.000000,10486.000000,1.226100e+04,10641.000000,10466.000000
mean,65.141998,16.826238,493.405921,4.337641,5.983675e+04,4.514134,4.228960
std,91.980429,36.368984,825.364580,0.652051,1.638115e+05,0.518865,0.660282
min,2.272400,1.000000,1.000000,1.000000,6.300000e+02,1.800000,1.000000
25%,19.990000,2.000000,97.000000,4.000000,2.103400e+04,4.300000,4.000000
50%,36.587800,6.000000,216.000000,4.500000,4.206900e+04,4.700000,4.300000
75%,70.192200,13.000000,544.000000,4.800000,7.092200e+04,5.000000,4.700000
max,1104.870000,367.000000,7541.000000,5.000000,2.000431e+06,5.000000,5.000000

In [23]:
# Find LEGO sets with star_rating >= 4
high_rating_lego_sets = df[df["star_rating"] >= 4]

# Display first 5 rows of the filtered dataset
high_rating_lego_sets.head()

,list_price,num_reviews,piece_count,play_star_rating,prod_id,review_difficulty,star_rating,val_star_rating
0,29.99,2.0,277,4.0,75823,Average,4.5,4.0
1,19.99,2.0,168,4.0,75822,Easy,5.0,4.0
2,12.99,11.0,74,4.3,75821,Easy,4.3,4.1
3,99.99,23.0,1032,3.6,21030,Average,4.6,4.3
4,79.99,14.0,744,3.2,21035,Challenging,4.6,4.1

In [24]:
# Count the number of LEGO sets with star_rating >= 4
high_rating_count = high_rating_lego_sets["star_rating"].count()
print(f"Total LEGO sets with star rating >= 4: {high_rating_count}")

Total LEGO sets with star rating >= 4: 9563

In [25]:
# Find the average price of high-rated LEGO sets
average_price_high_rating = high_rating_lego_sets["list_price"].mean()
print(f"Average price of LEGO sets with star rating >= 4: ${average_price_high_rating:.2f}")

Average price of LEGO sets with star rating >= 4: $68.25

In [26]:
# ✅ Step 1: Mount Google Drive
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# ✅ Step 2: Define File Path (Modify if needed)
file_path = "/content/drive/My Drive/lego_setsHB.csv"

# ✅ Step 3: Read Dataset
df = pd.read_csv(file_path)

# ✅ Step 4: Dataset Overview
print("\n🔍 **Dataset Overview**")
print("--------------------------------------------------")
df.info()

print("\n📊 **Dataset Summary Statistics**")
print("--------------------------------------------------")
print(df.describe())

# ✅ Step 5: Filter LEGO Sets with Star Rating >= 4
high_rating_lego_sets = df[df["star_rating"] >= 4]

# ✅ Step 6: Count the Number of High-Rated LEGO Sets
high_rating_count = high_rating_lego_sets["star_rating"].count()

# ✅ Step 7: Calculate the Average List Price for High-Rated Sets
average_price_high_rating = high_rating_lego_sets["list_price"].mean()

# ✅ Step 8: Display Clean Output
print("\n🎯 **LEGO Data Analysis Results**")
print("--------------------------------------------------")
print(f"✔️ Total LEGO Sets: {len(df):,}")
print(f"✔️ High-Rated LEGO Sets (⭐ ≥ 4.0): {high_rating_count:,}")
print(f"✔️ Average Price of High-Rated LEGO Sets: ${average_price_high_rating:.2f}")

# ✅ Step 9: Show a Sample of High-Rated LEGO Sets
print("\n📌 **Sample LEGO Sets with ⭐ Rating ≥ 4.0**")
print("--------------------------------------------------")
display(high_rating_lego_sets.head(10))  # Displays first 10 rows in Colab-friendly format

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

🔍 **Dataset Overview**
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   list_price         12261 non-null  float64
 1   num_reviews        10641 non-null  float64
 2   piece_count        12261 non-null  int64
 3   play_star_rating   10486 non-null  float64
 4   prod_id            12261 non-null  int64
 5   review_difficulty  10206 non-null  object
 6   star_rating        10641 non-null  float64
 7   val_star_rating    10466 non-null  float64
dtypes: float64(5), int64(2), object(1)
memory usage: 766.4+ KB

📊 **Dataset Summary Statistics**
--------------------------------------------------
         list_price   num_reviews   piece_count  play_star_rating  \
count  12261.000000  10641.000000  12261.000000      10486.000000
mean      65.141998     16.826238    493.405921          4.337641
std       91.980429     36.368984    825.364580          0.652051
min        2.272400      1.000000      1.000000          1.000000
25%       19.990000      2.000000     97.000000          4.000000
50%       36.587800      6.000000    216.000000          4.500000
75%       70.192200     13.000000    544.000000          4.800000
max     1104.870000    367.000000   7541.000000          5.000000

            prod_id   star_rating  val_star_rating
count  1.226100e+04  10641.000000     10466.000000
mean   5.983675e+04      4.514134         4.228960
std    1.638115e+05      0.518865         0.660282
min    6.300000e+02      1.800000         1.000000
25%    2.103400e+04      4.300000         4.000000
50%    4.206900e+04      4.700000         4.300000
75%    7.092200e+04      5.000000         4.700000
max    2.000431e+06      5.000000         5.000000

🎯 **LEGO Data Analysis Results**
--------------------------------------------------
✔️ Total LEGO Sets: 12,261
✔️ High-Rated LEGO Sets (⭐ ≥ 4.0): 9,563
✔️ Average Price of High-Rated LEGO Sets: $68.25

📌 **Sample LEGO Sets with ⭐ Rating ≥ 4.0**
--------------------------------------------------

,list_price,num_reviews,piece_count,play_star_rating,prod_id,review_difficulty,star_rating,val_star_rating
0,29.99,2.0,277,4.0,75823,Average,4.5,4.0
1,19.99,2.0,168,4.0,75822,Easy,5.0,4.0
2,12.99,11.0,74,4.3,75821,Easy,4.3,4.1
3,99.99,23.0,1032,3.6,21030,Average,4.6,4.3
4,79.99,14.0,744,3.2,21035,Challenging,4.6,4.1
5,59.99,7.0,597,3.7,21039,Average,4.9,4.4
6,59.99,37.0,598,3.7,21028,Average,4.2,4.1
7,49.99,24.0,780,4.4,21029,Average,4.7,4.3
8,39.99,23.0,468,3.6,21034,Average,4.7,4.1
9,39.99,11.0,444,3.6,21033,Average,4.8,4.5